export const expense = [
    {
        id: 1,
        amount: 310,
        date: "03-03-2024",
        category: "Shopping",
        remarks: "Test Remarks",
    },
    {
        id: 2,
        amount: 500,
        date: "04-03-2024",
        category: "Salary",
        remarks: "Monthly Salary",
    },
    {
        id: 3,
        amount: 120,
        date: "07-03-2024",
        category: "Freelance",
        remarks: "Project Payment",
    },
    {
        id: 4,
        amount: 80,
        date: "10-03-2024",
        category: "Gift",
        remarks: "Birthday Gift",
    },
    {
        id: 5,
        amount: 200,
        date: "12-03-2024",
        category: "Bonus",
        remarks: "Performance Bonus",
    },
    {
        id: 6,
        amount: 150,
        date: "05-03-2024",
        category: "Dividends",
        remarks: "Investment Returns",
    },
    {
        id: 7,
        amount: 300,
        date: "06-03-2024",
        category: "Consulting",
        remarks: "Consulting Fee",
    },
    {
        id: 8,
        amount: 180,
        date: "08-03-2024",
        category: "Online Sales",
        remarks: "Product Sales",
    },
    {
        id: 9,
        amount: 250,
        date: "09-03-2024",
        category: "Rent",
        remarks: "Rental Income",
    },
    {
        id: 10,
        amount: 400,
        date: "11-03-2024",
        category: "Commission",
        remarks: "Sales Commission",
    },
    {
        id: 11,
        amount: 600,
        date: "12-03-2024",
        category: "Contract Work",
        remarks: "Contract Payment",
    },
];