export const income = [
    {
        id: 1,
        amount: 210,
        date: "03-03-2024",
        category: "Shopping",
        remarks: "Test Remarks",
    },
    {
        id: 2,
        amount: 1500,
        date: "04-03-2024",
        category: "Salary",
        remarks: "Monthly Salary",
    },
    {
        id: 3,
        amount: 70,
        date: "07-03-2024",
        category: "Freelance",
        remarks: "Project Payment",
    },
    {
        id: 4,
        amount: 4400,
        date: "10-03-2024",
        category: "Gift",
        remarks: "Birthday Gift",
    },
    {
        id: 5,
        amount: 0,
        date: "12-03-2024",
        category: "Bonus",
        remarks: "Performance Bonus",
    },
    {
        id: 6,
        amount: 900,
        date: "05-03-2024",
        category: "Dividends",
        remarks: "Investment Returns",
    },
    {
        id: 7,
        amount: 0,
        date: "06-03-2024",
        category: "Consulting",
        remarks: "Consulting Fee",
    },
    {
        id: 8,
        amount: 12000,
        date: "08-03-2024",
        category: "Online Sales",
        remarks: "Product Sales",
    },
    {
        id: 9,
        amount: 360,
        date: "09-03-2024",
        category: "Rent",
        remarks: "Rental Income",
    },
    {
        id: 10,
        amount: 4400,
        date: "11-03-2024",
        category: "Commission",
        remarks: "Sales Commission",
    },
    {
        id: 11,
        amount: 2100,
        date: "12-03-2024",
        category: "Contract Work",
        remarks: "Contract Payment",
    },
];
